### ISSUE TITLE
Feature 1: User can create an account. 

### ISSUE THREAD

**Issue by annuhpark** [annuhpark/solitudal-thoughts#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create an account with e-mail and password. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="422" alt="Screen Shot 2022-05-31 at 11 40 12 AM" src="https://user-images.githubusercontent.com/69396309/171261613-b559d1a1-8257-4203-a4e7-7a1a0ec09e5e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to create the users table in public schema. 
- [ ] Update `data.sql` to add users table with userId, email, & password. 

### ☁️ Server

- [ ] Update `server/index.js` to use the post method. Follow instructions below:
- [ ]    * Hash the user's password with `argon2.hash()`
   * Then, 😉
   *   Insert the user's "email" and "hashedPassword" into the "users" table.
   *   Then, 😉
   *     Respond to the client with a 201 status code and the new user's "email", "username", and "createdAt" timestamp.
   *   Catch any errors.
   * Catch any errors.
- [ ] Test your server with the HTTPie command by sending an email and a password in the body of a POST request.
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a new JSX file for signing up. 
- [ ] Create a component to sign-up for an account using email & password. 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
